calendars:
  calendar_name:
    color: '#00ff00'
    calendar_id: calendarid@group.calendar.google.com
    private_key: 
default_color: '#efefef'
lookahead: 30 # days
timezone: Pacific/Auckland
apps_domain: example.com